### ISSUE TITLE
Problems installing mumu

### ISSUE THREAD

**Issue by CristinaZb** [frederic-mahe/mumu#2]
Helloo
I'd like to use mumu but I got problems with the installation:
```
git clone https://github.com/frederic-mahe/mumu.git
Clonando en 'mumu'...
remote: Enumerating objects: 1356, done.
remote: Total 1356 (delta 0), reused 0 (delta 0), pack-reused 1356
Recibiendo objetos: 100% (1356/1356), 180.64 KiB | 314.00 KiB/s, listo.
Resolviendo deltas: 100% (907/907), listo.

cd mumu/

make
g++ -std=c++2a -Wall -Wextra -g -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wnull-dereference -Wuseless-cast -Wdouble-promotion -Wformat=2 -O3 -DNDEBUG -flto -c src/search_parent.cpp -o src/search_parent.o
In file included from src/search_parent.cpp:28:
src/mumu.h:73:16: error: declaration of ‘operator<=’ as non-function
   73 |   auto operator<=> (Match const& rhs) const {
      |                ^~
src/mumu.h:73:16: error: expected ‘;’ at end of member declaration
   73 |   auto operator<=> (Match const& rhs) const {
      |                ^~
      |                  ;
src/mumu.h:73:18: error: expected unqualified-id before ‘>’ token
   73 |   auto operator<=> (Match const& rhs) const {
      |                  ^
src/mumu.h:83:46: error: ‘bool Match::operator==(const Match&) const’ cannot be defaulted
   83 |   bool operator== (Match const& rhs) const = default;
      |                                              ^~~~~~~
make: *** [Makefile:39: src/search_parent.o] Error 1
```

I'm using **gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)** and **GNU Make 4.3**.
No idea what is going on... could you guide me?
Thank you.

**Comment by frederic-mahe** [comment]
Hello @CristinaZb 

sorry, you need **gcc** version 10 or more recent to be able to compile `mumu` (I use this project as a benchmark to implement and test recent C++ features). It seems that your operating system is Ubuntu LTS 20.04. You would need to upgrade to Ubuntu LTS 22.04 to get a more recent version of GCC.

Alternatively, if singularity or apptainer is already installed on your operating system, I can provide you with a SIF file containing a working image of `mumu` (total size is 4 MB). You might want to try to install [apptainer](https://apptainer.org/docs/user/main/quick_start.html), but the process is quite complicated. I've just tried on a fresh Ubuntu LTS 20.04 virtual machine and it failed miserably.

**Comment by CristinaZb** [comment]
Thank you for the comment Frederic.
I've upgraded the OS to 22.04 to get the gcc version 11.2.0 and now mumu is installed correctly.

**Comment by frederic-mahe** [comment]
Thank you for trying mumu!
