### ISSUE TITLE
Installation within conda environment

### ISSUE THREAD

**Issue by givdieri** [frederic-mahe/mumu#8]
I was trying to switch out LULU for MUMU in a bash program within a conda environment
Installation within an environment doesn't seem possible without these changes to the Makefile:
(If this doesn't make sense to you - I am not very knowledgeable in these matters)

(1) line 31
```Makefile
prefix ?= /usr/local
```
(2) line 85
```Makefile
install: $(PROG) $(MAN)
	mkdir -p $(DESTDIR)$(bindir)
	$(INSTALL_PROGRAM) $(PROG) $(DESTDIR)$(bindir)/
	mkdir -p $(DESTDIR)$(man1dir)
	$(INSTALL_PROGRAM) $(MAN) $(DESTDIR)$(man1dir)/
```

This allows to specify a conda environment to install in (e.g.):
```sh
make install DESTDIR=$(conda info --base)/envs/env_name
```

**Comment by frederic-mahe** [comment]
Hello @givdieri thanks for trying mumu. I took the liberty to edit your post to improve code markup. Commits efab5b3889a1590241202b8b4f544fbec8068dd2 and de8b93de2b07fc14d25d6bd810bcd6b1a0e3f313 add the changes you've suggested to the main branch.

Please close the issue if this new version works for you.
